" Make Vim more useful
set nocompatible

" NeoBundle auto-installation and setup {{{
    call plug#begin('~/.vim/plugged')

    " Bundles
        " Libs
            Plug 'Shougo/vimproc.vim', { 'do': 'make' }
        " Interface
            Plug 'bling/vim-airline'
            Plug 'scrooloose/nerdtree'
        " Colorschemes
            Plug 'joedicastro/vim-molokai256'
        " Editing
            " Snippets
            Plug 'SirVer/ultisnips'
            " To surround vim objects with a pair of identical chars
            Plug 'tpope/vim-surround'
            Plug 'scrooloose/nerdcommenter'
            Plug 'bronson/vim-trailing-whitespace'
            " Syntax checking
            Plug 'scrooloose/syntastic'
            Plug 'nathanaelkane/vim-indent-guides'
            Plug 'chase/vim-ansible-yaml'
            Plug 'Raimondi/delimitMate'
            Plug 'Valloric/YouCompleteMe', { 'do': './install.py' }
            " Align text
            Plug 'godlygeek/tabular'
            Plug 'mattn/emmet-vim'
        " Ruby
            Plug 'vim-ruby/vim-ruby'
        " PHP
            Plug 'php.vim'
        " Golang
            Plug 'fatih/vim-go'
        " Syntax support
            Plug 'ap/vim-css-color'
            Plug 'othree/html5.vim'
            Plug 'tsaleh/vim-tmux'
            Plug 'JSON.vim'
            Plug 'tpope/vim-cucumber'
            Plug 'tpope/vim-haml'
            Plug 'tpope/vim-markdown'
            Plug 'kchmck/vim-coffee-script'
            Plug 'vitaly/vim-syntastic-coffee'
            Plug 'vim-scripts/jade.vim'
            Plug 'wavded/vim-stylus'
            Plug 'slim-template/vim-slim'
            Plug 'elixir-lang/vim-elixir'
            Plug 'tfnico/vim-gradle'
            Plug 'neo4j-contrib/cypher-vim-syntax'
        " Support
            " extend repetitions by the 'dot' key
            Plug 'tpope/vim-repeat'
            " Run things asynchronously
            Plug 'tpope/vim-dispatch'

    call plug#end()
" }}}


filetype plugin indent on      " Indent and plugins by filetype
runtime macros/matchit.vim

" VIM Setup {{{ ===============================================================
    let mapleader=','
    let maplocalleader= ' '
    "Basic
        set ttimeoutlen=0       " toggle between modes almost instantly
        "set autoread            " automatically read file that has been changed on disk and doesn't have changes in vim
        set autowriteall        " Automatically save before commands like :next and :make
        set hidden              " enable multiple modified buffers
        set history=1000        " Store a lots of history commands
    " Backup
        set nobackup            " Don't create backups
        set noswapfile          " Don't create swap files
    " Encoding
        set encoding=utf-8
        set termencoding=utf-8
        set fileencodings=utf8,cp1251
    " Interface
        set title               " Set title of the window to filename [+=-] (path) - VIM
        set showcmd             " Show (partial) command in status line.
        set scrolloff=5         " Minimal number of lines to keep above and below the cursor
        set ruler               " line and column number of the cursor position
        set laststatus=2        " always show the status line
        "set cursorline          " Highlight the screen line of the cursor
        set splitbelow          " Splitting a window will put the new window below the current one
        set splitright          " Splitting a window will put the new window right of the current one
        set backspace=indent,eol,start
    " Wildmenu
        set wildmenu                        " Command line autocompletion
        set wildmode=list:longest,full      " Shows all the options
        set wildignore+=*.sw?                            " Vim swap files
        set wildignore+=*.bak,*.?~,*.??~,*.???~,*.~      " Backup files
        set wildignore+=*.luac                           " Lua byte code
        set wildignore+=*.jar                            " java archives
        set wildignore+=*.pyc                            " Python byte code
        set wildignore+=*.stats                          " Pylint stats
    " Search
        set incsearch           " While typing a search command, show pattern matches as it is typed
        set hlsearch            " When there is a previous search pattern, highlight all its matches
        set ignorecase          " Ignore case in search patterns
        set smartcase           " Override the 'ignorecase' if the search pattern contains upper case characters
        set gdefault            " All matches in a line are substituted instead of one
    " Editor
        autocmd BufRead,BufNewFile *.md setlocal spell
        hi SpellErrors guibg=red guifg=black ctermbg=red ctermfg=black
        "set showtabline=2       " Always show tabs
        set list                " Display invisible characters
        set listchars=tab:▷⋅,trail:·
        set number              " Set line numbers
        set showmatch           " Show matching brackets.
        set nowrap              " Do not wrap words (view)
    " Tabs, Spaces
        set expandtab           " Use spaces instead of tab
        set shiftwidth=4        " Number of spaces to use for each step of (auto)indent
        set tabstop=4           " Number of spaces that a tab counts for
        set softtabstop=4       " Number of spaces that a tab counts for while performing editing operations
        set autoindent          " Copy indent from current line when starting a new line
        set smartindent         " Do smart indenting when starting a new line
        " File specific
            autocmd FileType ruby,coffee,haml,sass,yaml,scss setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2
    " Colorscheme
        syntax enable
        set t_Co=256            " Number of colors
        set background=dark
        colorscheme molokai256
        let g:indent_guides_auto_colors = 0
        autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=darkgrey ctermbg=black
        autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=darkgrey ctermbg=black
        set guifont=Ubuntu\ Mono\ 12
        let &colorcolumn=join(range(120,999),",")
    " Resize the divisions if the Vim window size changes
        au VimResized * exe 'normal! \<c-w>='
    " Enable omni completion.
        " Ruby completion
            autocmd FileType ruby let g:rubycomplete_buffer_loading = 1
            autocmd FileType ruby let g:rubycomplete_rails = 1
            autocmd FileType ruby let g:rubycomplete_classes_in_global = 1
            autocmd FileType ruby let g:rubycomplete_include_object = 1
            autocmd FileType ruby let g:rubycomplete_include_objectspace = 1
        autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
        autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
        autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
        autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
        autocmd FileType ruby set omnifunc=rubycomplete#Complete
        autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
" }}}

" Scortcuts {{{ ===============================================================
    " Edit {{{
        nmap \w :w!<CR>
    " }}}
    " Basic {{{
        " Clear the search highlight in Normal mode
        nnoremap <silent> <Esc><Esc> :nohlsearch<CR><Esc>
        " FixWhitespaces
        map <F5> :FixWhitespace<CR>
    " }}}
    " Windows {{{
        " Fast windows moves
        nmap <C-h> <C-W>h
        nmap <C-j> <C-W>j
        nmap <C-k> <C-W>k
        nmap <C-l> <C-W>l
        " New windows
        nnoremap <Leader>v <C-w>v
        nnoremap <Leader>h <C-w>s
        " Create a new window relative to the current one
        nmap <Leader><left>  :leftabove  vnew<CR>
        nmap <Leader><right> :rightbelow vnew<CR>
        nmap <Leader><up>    :leftabove  new<CR>
        nmap <Leader><down>  :rightbelow new<CR>
        " Fast window & buffer close and kill
        nnoremap <Leader>k <C-w>c
        nnoremap <silent><Leader>K :bd<CR>
        " Fast switch between two last windows
        nnoremap <leader><leader> <c-^>
    " }}}
    " Cut/Paste {{{
        " toggle paste mode
        map <Leader>P :set invpaste<CR>
        set clipboard=unnamed,unnamedplus
    " }}}
    " Spelling {{{
        " turn on the spell checking and set the English language
        nmap <Leader>se :setlocal spell spelllang=en<CR>
        " turn off the spell checking
        nmap <Leader>so :setlocal nospell <CR>
        " jump to the next bad spell word
        nmap <Leader>sn ]s
        " suggest words
        nmap <Leader>sp z=
        " jump to the next bad spell word and suggests a correct one
        nmap <Leader>sc ]sz=
        " add word to the dictionary
        nmap <Leader>sa zg
    " }}}
    " Search {{{
        " Search matches are always in center
        nmap n nzz
        nmap N Nzz
        nmap * *zz
        nmap # #zz
        nmap g* g*zz
        nmap g# g#zz
    " }}}
" }}}

" Plugins {{{=========================================================
    " Toggle line numbers {{{
        nnoremap <silent><Leader>l :call ToggleRelativeAbsoluteNumber()<CR>
        function! ToggleRelativeAbsoluteNumber()
          if !&number && !&relativenumber
              set number
              set norelativenumber
          elseif &number && !&relativenumber
              set nonumber
              set relativenumber
          elseif !&number && &relativenumber
              set number
              set relativenumber
          elseif &number && &relativenumber
              set nonumber
              set norelativenumber
          endif
        endfunction
    " }}}
    " NerdTree {{{
        " Toggle NERDTree
        map <C-x> :NERDTreeToggle<CR>
        let NERDTreeShowBookmarks=1
        let NERDTreeChDirMode=2
        let NERDTreeQuitOnOpen=1
        let NERDTreeShowHidden=1
        let NERDTreeKeepTreeInNewTab=0
        let NERDTreeMinimalUI=1
        let NERDTreeDirArrows=1
        let NERDTreeIgnore=['\.idea$', '\.git$', 'TAGS', '*.iml']
        let g:NERDTreeWinPos = "right""
    " }}}
    " Nerd Comment {{{
        nmap <leader>/ :call NERDComment(0, "invert")<cr>
        vmap <leader>/ :call NERDComment(0, "invert")<cr>
    " }}}
    " Airline {{{
        let g:airline_theme='powerlineish'
        let g:airline#extensions#hunks#non_zero_only = 1
        let g:airline_powerline_fonts = 1
    " }}}
    " Synastic {{{
        let g:syntastic_enable_signs=1
        let g:syntastic_auto_loc_list=2
        let g:syntastic_check_on_wq=0
        let g:syntastic_check_on_open=1
        let g:syntastic_error_symbol='✗'
        let g:syntastic_warning_symbol='⚠'
        let g:syntastic_style_error_symbol  = '⚡'
        let g:syntastic_style_warning_symbol  = '⚡'
    " }}}
    " YouCompleteMe {{{
        let g:ycm_complete_in_comments = 1
        let g:ycm_collect_identifiers_from_tags_files = 1
        let g:ycm_key_invoke_completion = '<C-Space>'
        let g:ycm_cache_omnifunc = 1
    " }}}
    " Indent-guides {{{
        let g:indent_guides_start_level = 2
        let g:indent_guides_enable_on_vim_startup = 1
        let g:indent_guides_guide_size = 1
        let g:indent_guides_color_change_percent = 5
    " }}}
    " Delimitmate {{{
        let delimitMate_expand_space = 1
    " }}}
    " Tabularize {{{
        nmap <Leader>a= :Tabularize /=<CR>
        vmap <Leader>a= :Tabularize /=<CR>
        nmap <Leader>a: :Tabularize /:\zs<CR>
        vmap <Leader>a: :Tabularize /:\zs<CR>
    " }}}
    " Golang {{{
        " Execute go code
        au FileType go nmap \r <Plug>(go-run)
        au FileType go nmap \b <Plug>(go-build)
        au FileType go nmap \t :GoTest!<cr>
        au FileType go nmap \c <Plug>(go-coverage)

        " Go to definition
        au FileType go nmap \dd <Plug>(go-def)
        au FileType go nmap \ds <Plug>(go-def-split)
        au FileType go nmap \dv <Plug>(go-def-vertical)

        " Open documentation
        au FileType go nmap \gd <Plug>(go-doc)
        au FileType go nmap \gv <Plug>(go-doc-vertical)
        au FileType go nmap \gb <Plug>(go-doc-browser)

        " Show a list of interfaces which is implemented by the type under your cursor
        au FileType go nmap \s <Plug>(go-implements)

        " Rename the identifier under the cursor to a new name
        au FileType go nmap \e <Plug>(go-rename)

        let g:go_highlight_functions = 1
        let g:go_highlight_methods = 1
        let g:go_highlight_structs = 1
        let g:go_highlight_operators = 1
        let g:go_highlight_build_constraints = 1

        let g:go_fmt_command = "goimports"

        let g:go_auto_type_info = 1
    " }}}
" }}}
