" Make Vim more useful
set nocompatible

" NeoBundle auto-installation and setup {{{
    " Auto installing NeoBundle
    let iCanHazNeoBundle=1
    let neobundle_readme=expand($HOME.'/.vim/bundle/neobundle.vim/README.md')
    if !filereadable(neobundle_readme)
        echo "Installing NeoBundle.."
        echo ""
        silent !mkdir -p $HOME/.vim/bundle
        silent !git clone https://github.com/Shougo/neobundle.vim $HOME/.vim/bundle/neobundle.vim
        let iCanHazNeoBundle=0
    endif

    " Call NeoBundle
    if has('vim_starting')
        set rtp+=$HOME/.vim/bundle/neobundle.vim/
    endif

    call neobundle#begin(expand('~/.vim/bundle/'))
    NeoBundleFetch 'Shougo/neobundle.vim'

    " Bundles
        " Libs
            NeoBundle 'L9'
            NeoBundle "MarcWeber/vim-addon-mw-utils"
            NeoBundle "tomtom/tlib_vim"
            " Vimproc to asynchronously run commands (NeoBundle, Unite)
            NeoBundle 'Shougo/vimproc', {
                  \ 'build' : {
                  \     'windows' : 'make -f make_mingw32.mak',
                  \     'cygwin' : 'make -f make_cygwin.mak',
                  \     'mac' : 'make -f make_mac.mak',
                  \     'unix' : 'make -f make_unix.mak',
                  \    },
                  \ }
        " Interface
            " A better looking status line
            NeoBundle 'bling/vim-airline'
            " Sidebar with file navigation
            NeoBundle 'scrooloose/nerdtree'
            " Fily FuzzySearch
            NeoBundle 'wincent/Command-T'
        " Colorschemes
            " Dark themes
                NeoBundle 'joedicastro/vim-molokai256'
                NeoBundle 'tomasr/molokai'
                NeoBundle 'sjl/badwolf'
                NeoBundle 'nielsmadan/harlequin'
                NeoBundle 'jpo/vim-railscasts-theme'
                NeoBundle '29decibel/codeschool-vim-theme'
                NeoBundle 'vividchalk.vim'
            " Light themes
                NeoBundle 'vim-scripts/summerfruit256.vim'
                NeoBundle 'joedicastro/vim-github256'
        " Editing
            " Snippets
            NeoBundle "SirVer/ultisnips"
            " To surround vim objects with a pair of identical chars
            NeoBundle 'tpope/vim-surround'
            NeoBundle 'scrooloose/nerdcommenter'
            NeoBundle "bronson/vim-trailing-whitespace"
            " Syntax checking
            NeoBundle "scrooloose/syntastic"
            NeoBundle "nathanaelkane/vim-indent-guides"
            NeoBundle 'Lokaltog/vim-easymotion'
            NeoBundle 'chase/vim-ansible-yaml'
            NeoBundle 'Raimondi/delimitMate'
            NeoBundle 'Valloric/YouCompleteMe'
            NeoBundle 'kana/vim-textobj-user'
            NeoBundle 'nelstrom/vim-textobj-rubyblock'
            " Align text
            NeoBundle 'godlygeek/tabular'
            NeoBundle 'mattn/emmet-vim'
        " Ruby
            NeoBundle 'vim-ruby/vim-ruby'
            NeoBundle 'tpope/vim-rails.git'
            NeoBundle 'tpope/vim-bundler'
            NeoBundle 'tpope/vim-rake'
            NeoBundle 'thoughtbot/vim-rspec'
            NeoBundle 'stefanoverna/vim-i18n'
            NeoBundle 'Keithbsmiley/rspec.vim'
        " PHP
            NeoBundle 'php.vim'
        " Clojure [DISABLED]
            " NeoBundle 'tpope/vim-classpath'
            " NeoBundle 'paredit.vim'
            " NeoBundle 'amdt/vim-niji'
            " NeoBundle 'tpope/vim-fireplace'
            " NeoBundle 'tpope/vim-leiningen'
            " NeoBundle 'guns/vim-clojure-static'
            " NeoBundle 'guns/vim-clojure-highlight'
        " Syntax support
            NeoBundle 'ap/vim-css-color'
            NeoBundle 'othree/html5.vim'
            NeoBundle 'tsaleh/vim-tmux'
            NeoBundle 'JSON.vim'
            NeoBundle 'tpope/vim-cucumber'
            NeoBundle 'tpope/vim-haml'
            NeoBundle 'tpope/vim-markdown'
            NeoBundle 'kchmck/vim-coffee-script'
            NeoBundle 'vitaly/vim-syntastic-coffee'
            NeoBundle 'vim-scripts/jade.vim'
            NeoBundle 'wavded/vim-stylus'
            NeoBundle 'slim-template/vim-slim'
            NeoBundle 'elixir-lang/vim-elixir'
            NeoBundle 'tfnico/vim-gradle'
        " Support
            " extend repetitions by the 'dot' key
            NeoBundle 'tpope/vim-repeat'
            " Run things asynchronously
            NeoBundle 'tpope/vim-dispatch'
    " First-time plugins installation
    if iCanHazNeoBundle == 0
        echo "Installing Bundles, please ignore key map error messages"
        echo ""
        :NeoBundleInstall
    endif
    NeoBundleCheck
    call neobundle#end()
" }}}

filetype plugin indent on      " Indent and plugins by filetype
runtime macros/matchit.vim

" VIM Setup {{{ ===============================================================
    let mapleader=','
    let maplocalleader= ' '
    "Basic
        set ttimeoutlen=0       " toggle between modes almost instantly
        "set autoread            " automatically read file that has been changed on disk and doesn't have changes in vim
        set autowriteall        " Automatically save before commands like :next and :make
        set hidden              " enable multiple modified buffers
        set history=1000        " Store a lots of history commands
    " Backup
        set nobackup            " Don't create backups
        set noswapfile          " Don't create swap files
    " Encoding
        set encoding=utf-8
        set termencoding=utf-8
        set fileencodings=utf8,cp1251
    " Interface
        set title               " Set title of the window to filename [+=-] (path) - VIM
        set showcmd             " Show (partial) command in status line.
        set scrolloff=5         " Minimal number of lines to keep above and below the cursor
        set ruler               " line and column number of the cursor position
        set laststatus=2        " always show the status line
        "set cursorline          " Highlight the screen line of the cursor
        set splitbelow          " Splitting a window will put the new window below the current one
        set splitright          " Splitting a window will put the new window right of the current one
        set backspace=indent,eol,start
    " Wildmenu
        set wildmenu                        " Command line autocompletion
        set wildmode=list:longest,full      " Shows all the options
        set wildignore+=*.sw?                            " Vim swap files
        set wildignore+=*.bak,*.?~,*.??~,*.???~,*.~      " Backup files
        set wildignore+=*.luac                           " Lua byte code
        set wildignore+=*.jar                            " java archives
        set wildignore+=*.pyc                            " Python byte code
        set wildignore+=*.stats                          " Pylint stats
    " Search
        set incsearch           " While typing a search command, show pattern matches as it is typed
        set hlsearch            " When there is a previous search pattern, highlight all its matches
        set ignorecase          " Ignore case in search patterns
        set smartcase           " Override the 'ignorecase' if the search pattern contains upper case characters
        set gdefault            " All matches in a line are substituted instead of one
    " Editor
        autocmd BufRead,BufNewFile *.md setlocal spell
        hi SpellErrors guibg=red guifg=black ctermbg=red ctermfg=black
        "set showtabline=2       " Always show tabs
        set list                " Display invisible characters
        set listchars=tab:▷⋅,trail:·
        set number              " Set line numbers
        set showmatch           " Show matching brackets.
        set nowrap              " Do not wrap words (view)
    " Tabs, Spaces
        set expandtab           " Use spaces instead of tab
        set shiftwidth=4        " Number of spaces to use for each step of (auto)indent
        set tabstop=4           " Number of spaces that a tab counts for
        set softtabstop=4       " Number of spaces that a tab counts for while performing editing operations
        set autoindent          " Copy indent from current line when starting a new line
        set smartindent         " Do smart indenting when starting a new line
        " File specific
            autocmd FileType ruby,coffee,haml,sass,yaml,scss setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2
    " GUI
        set go-=T               " hide the toolbar
        set go-=m               " hide the menu
        " The next two lines are quite tricky, but in Gvim, if you don't do this, if you
        " only hide all the scrollbars, the vertical scrollbar is showed anyway
        set go+=rRlLbh                  " show all the scrollbars
        set go-=rRlLbh                  " hide all the scrollbars
        set ttyfast                     " better screen redraw
        set lazyredraw                  " only redraws if it is needed
    " Colorscheme
        syntax enable
        set t_Co=256            " Number of colors
        set background=dark
        if has("gui_running")
            colorscheme railscasts
        else
            colorscheme molokai256
            let g:indent_guides_auto_colors = 0
            autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=darkgrey ctermbg=black
            autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=darkgrey ctermbg=black
        endif
        set guifont=Ubuntu\ Mono\ 12
        let &colorcolumn=join(range(120,999),",")
    " Resize the divisions if the Vim window size changes
        au VimResized * exe 'normal! \<c-w>='
    " Enable omni completion.
        " Ruby completion
            autocmd FileType ruby let g:rubycomplete_buffer_loading = 1
            autocmd FileType ruby let g:rubycomplete_rails = 1
            autocmd FileType ruby let g:rubycomplete_classes_in_global = 1
            autocmd FileType ruby let g:rubycomplete_include_object = 1
            autocmd FileType ruby let g:rubycomplete_include_objectspace = 1
        autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
        autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
        autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
        autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
        autocmd FileType ruby set omnifunc=rubycomplete#Complete
        autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
    " ClojureScript support
        autocmd BufRead,BufNewFile *.cljs setlocal filetype=clojure
        " ClojureScript repl
        command! Wiggie :Piggieback (weasel.repl.websocket/repl-env :ip "0.0.0.0" :port 9001)
" }}}

" Scortcuts {{{ ===============================================================
    " Basic {{{
        " Clear the search highlight in Normal mode
        nnoremap <silent> <Esc><Esc> :nohlsearch<CR><Esc>
        " FixWhitespaces
        map <F5> :FixWhitespace<CR>
    " }}}
    " Quick exiting without save {{{
        nnoremap <Leader>`` :qa!<CR>
    " }}}
    " Windows {{{
        " Fast windows moves
        nmap <C-h> <C-W>h
        nmap <C-j> <C-W>j
        nmap <C-k> <C-W>k
        nmap <C-l> <C-W>l
        " New windows
        nnoremap <Leader>v <C-w>v
        nnoremap <Leader>h <C-w>s
        " Create a new window relative to the current one
        nmap <Leader><left>  :leftabove  vnew<CR>
        nmap <Leader><right> :rightbelow vnew<CR>
        nmap <Leader><up>    :leftabove  new<CR>
        nmap <Leader><down>  :rightbelow new<CR>
        " Fast window & buffer close and kill
        nnoremap <Leader>k <C-w>c
        nnoremap <silent><Leader>K :bd<CR>
        " Fast switch between two last windows
        nnoremap <leader><leader> <c-^>
    " }}}
    " Cut/Paste {{{
        " toggle paste mode
        map <Leader>P :set invpaste<CR>
        set clipboard=unnamed,unnamedplus
    " }}}
    " Spelling {{{
        " turn on the spell checking and set the English language
        nmap <Leader>se :setlocal spell spelllang=en<CR>
        " turn off the spell checking
        nmap <Leader>so :setlocal nospell <CR>
        " jump to the next bad spell word
        nmap <Leader>sn ]s
        " suggest words
        nmap <Leader>sp z=
        " jump to the next bad spell word and suggests a correct one
        nmap <Leader>sc ]sz=
        " add word to the dictionary
        nmap <Leader>sa zg
    " }}}
    " Search {{{
        " Search matches are always in center
        nmap n nzz
        nmap N Nzz
        nmap * *zz
        nmap # #zz
        nmap g* g*zz
        nmap g# g#zz
    " }}}
    " Tags {{{
        " Reload tags
        map <Leader>rt :!ctags --fields=+l --languages=-javascript --exclude=.git --exclude='*.log' -R * `bundle show --paths`<CR><CR>
    " }}}
    " Rails {{{
        map <leader>gr :topleft :split config/routes.rb<cr>
        map <leader>gg :topleft :split Gemfile<cr>
        map <leader>ge :topleft :vsplit config/locales/en.yml<cr>
    " }}}
" }}}

" Plugins {{{=========================================================
    " Toggle line numbers {{{
        nnoremap <silent><Leader>l :call ToggleRelativeAbsoluteNumber()<CR>
        function! ToggleRelativeAbsoluteNumber()
          if !&number && !&relativenumber
              set number
              set norelativenumber
          elseif &number && !&relativenumber
              set nonumber
              set relativenumber
          elseif !&number && &relativenumber
              set number
              set relativenumber
          elseif &number && &relativenumber
              set nonumber
              set norelativenumber
          endif
        endfunction
    " }}}
    " NerdTree {{{
        " Toggle NERDTree
        map <C-x> :NERDTreeToggle<CR>
        let NERDTreeShowBookmarks=1
        let NERDTreeChDirMode=2
        let NERDTreeQuitOnOpen=1
        let NERDTreeShowHidden=1
        let NERDTreeKeepTreeInNewTab=0
        let NERDTreeMinimalUI=1
        let NERDTreeDirArrows=1
        let NERDTreeIgnore=['\.idea$', '\.git$', 'TAGS']
        let g:NERDTreeWinPos = "right""
    " }}}
    " Run RSPec tests {{{
        if has("gui_running")
            let g:rspec_command = "!rspec --no-color {spec}"
        else
            let g:rspec_command = "!rspec {spec}"
        endif
        map <Leader>tf :call RunCurrentSpecFile()<CR>
        map <Leader>tn :call RunNearestSpec()<CR>
        map <Leader>tl :call RunLastSpec()<CR>
        map <Leader>ta :call RunAllSpecs()<CR>
    " }}}
    " Nerd Comment {{{
        nmap <leader>/ :call NERDComment(0, "invert")<cr>
        vmap <leader>/ :call NERDComment(0, "invert")<cr>
    " }}}
    " Rails/i18n translate {{{
        vmap <Leader>z :call I18nTranslateString()<CR>
    " }}}
    " Swich {{{
        map <Leader>w :Switch<CR>
        autocmd FileType haml let b:switch_definitions =
            \ [
            \   g:switch_builtins.ruby_hash_style,
            \   g:switch_builtins.ruby_string,
            \   g:switch_builtins.true_false,
            \   g:switch_builtins.true_false,
            \ ]
    " }}}
    " Airline {{{
        let g:airline_theme='powerlineish'
        " Deprecated
        " let g:airline_enable_branch=1
        " let g:airline_detect_whitespace = 1
        let g:airline#extensions#hunks#non_zero_only = 1
    " }}}
    " Synastic {{{
        let g:syntastic_enable_signs=1
        let g:syntastic_auto_loc_list=2
        let g:syntastic_check_on_wq=0
        let g:syntastic_check_on_open=1
        let g:syntastic_error_symbol='✗'
        let g:syntastic_warning_symbol='⚠'
        let g:syntastic_style_error_symbol  = '⚡'
        let g:syntastic_style_warning_symbol  = '⚡'
    " }}}
    " YouCompleteMe {{{
        let g:ycm_complete_in_comments = 1
        let g:ycm_collect_identifiers_from_tags_files = 1
        "let g:ycm_autoclose_preview_window_after_completion = 1
        "let g:ycm_autoclose_preview_window_after_insertion = 1
        "let g:ycm_key_list_select_completion = ['<Down>']
        "let g:ycm_key_list_previous_completion = ['<Up>']
        let g:ycm_key_invoke_completion = '<C-Space>'
        let g:ycm_cache_omnifunc = 1
    " }}}
    " Indent-guides {{{
        let g:indent_guides_start_level = 2
        let g:indent_guides_enable_on_vim_startup = 1
        let g:indent_guides_guide_size = 1
        let g:indent_guides_color_change_percent = 5
    " }}}
    " Delimitmate {{{
        let delimitMate_expand_space = 1
    " }}}
    " Tabularize {{{
        nmap <Leader>a= :Tabularize /=<CR>
        vmap <Leader>a= :Tabularize /=<CR>
        nmap <Leader>a: :Tabularize /:\zs<CR>
        vmap <Leader>a: :Tabularize /:\zs<CR>
    " }}}
    " Command-T {{{
        map <leader>grr :topleft :split config/routes.rb<cr>
        map <leader>grg :topleft :split Gemfile<cr>
        map <leader>gre :topleft :vsplit config/locales/en.yml<cr>
        map <leader>grv :CommandTFlush<cr>\|:CommandT app/views<cr>
        map <leader>gra :CommandTFlush<cr>\|:CommandT app/assets<cr>
        map <leader>gri :CommandTFlush<cr>\|:CommandT app/assets/images<cr>
        map <leader>grj :CommandTFlush<cr>\|:CommandT app/assets/javascripts<cr>
        map <leader>grs :CommandTFlush<cr>\|:CommandT app/assets/stylesheets<cr>
        map <leader>grc :CommandTFlush<cr>\|:CommandT app/controllers<cr>
        map <leader>grm :CommandTFlush<cr>\|:CommandT app/models<cr>
        map <leader>grh :CommandTFlush<cr>\|:CommandT app/helpers<cr>
        map <leader>grl :CommandTFlush<cr>\|:CommandT lib<cr>
        map <leader>grt :CommandTFlush<cr>\|:CommandT spec<cr>
        map <leader>gf :CommandTFlush<cr>\|:CommandT<cr>
    " }}}
" }}}
