command_timeout=200

[cmd_duration]
min_time=1000
show_milliseconds=false

[aws]
disabled=true

[rust]
disabled=true

[package]
disabled=true

[nodejs]
disabled=true

[python]
disabled=false

[cmake]
disabled=true

[java]
disabled=true

[php]
disabled=true

[docker_context]
disabled=true

[gradle]
disabled=true

[lua]
disabled=true
